import torch

from comfy_api.latest import io


class DropAlpha(io.ComfyNode):
    @classmethod
    def define_schema(cls) -> io.Schema:
        return io.Schema(
            node_id="DropAlpha",
            display_name="Drop Alpha",
            category="AlxNodes",
            description=(
                "Strips the alpha channel from an input image and outputs the RGB image. When "
                "passing a RGBA image generated by a model (e.g., Qwen-Image-2.1) to a node like "
                "RTX Video Super Resolution, this can be useful."
            ),
            search_aliases=[
                "alpha",
                "rgb",
                "rgba",
                "remove alpha",
            ],
            inputs=[
                io.Image.Input("image"),
            ],
            outputs=[
                io.Image.Output("IMAGE"),
            ],
        )

    @classmethod
    def execute(cls, image: torch.Tensor) -> io.NodeOutput:
        if image.dim() != 4 or image.shape[-1] < 3:
            return image

        # Keep R, G, B (and any channel before a trailing alpha); drop the tail.
        output = image[..., :3].clone().to(torch.float32)
        return io.NodeOutput(output)
